# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cncpp_machine_create <- function(filename) {
    .Call(`_cncppr_cncpp_machine_create`, filename)
}

cncpp_machine_desc <- function(machine, colored) {
    .Call(`_cncppr_cncpp_machine_desc`, machine, colored)
}

cncpp_machine_load <- function(machine, filename) {
    invisible(.Call(`_cncppr_cncpp_machine_load`, machine, filename))
}

cncpp_machine_quantize <- function(machine, time) {
    .Call(`_cncppr_cncpp_machine_quantize`, machine, time)
}

cncpp_machine_A <- function(machine) {
    .Call(`_cncppr_cncpp_machine_A`, machine)
}

cncpp_machine_tq <- function(machine) {
    .Call(`_cncppr_cncpp_machine_tq`, machine)
}

cncpp_machine_fmax <- function(machine) {
    .Call(`_cncppr_cncpp_machine_fmax`, machine)
}

cncpp_machine_error <- function(machine) {
    .Call(`_cncppr_cncpp_machine_error`, machine)
}

cncpp_machine_max_error <- function(machine) {
    .Call(`_cncppr_cncpp_machine_max_error`, machine)
}

cncpp_machine_zero <- function(machine) {
    .Call(`_cncppr_cncpp_machine_zero`, machine)
}

cncpp_machine_offset <- function(machine) {
    .Call(`_cncppr_cncpp_machine_offset`, machine)
}

cncpp_machine_setpoint <- function(machine) {
    .Call(`_cncppr_cncpp_machine_setpoint`, machine)
}

cncpp_machine_position <- function(machine) {
    .Call(`_cncppr_cncpp_machine_position`, machine)
}

cncpp_machine_set_setpoint <- function(machine, point) {
    invisible(.Call(`_cncppr_cncpp_machine_set_setpoint`, machine, point))
}

cncpp_machine_set_setpoint_xyz <- function(machine, x, y, z) {
    invisible(.Call(`_cncppr_cncpp_machine_set_setpoint_xyz`, machine, x, y, z))
}

cncpp_machine_set_position <- function(machine, point) {
    invisible(.Call(`_cncppr_cncpp_machine_set_position`, machine, point))
}

cncpp_machine_summary <- function(machine) {
    .Call(`_cncppr_cncpp_machine_summary`, machine)
}

cncpp_point_create <- function(x, y, z) {
    .Call(`_cncppr_cncpp_point_create`, x, y, z)
}

cncpp_point_desc <- function(point, colored) {
    .Call(`_cncppr_cncpp_point_desc`, point, colored)
}

cncpp_point_is_complete <- function(point) {
    .Call(`_cncppr_cncpp_point_is_complete`, point)
}

cncpp_point_reset <- function(point) {
    invisible(.Call(`_cncppr_cncpp_point_reset`, point))
}

cncpp_point_x <- function(point) {
    .Call(`_cncppr_cncpp_point_x`, point)
}

cncpp_point_y <- function(point) {
    .Call(`_cncppr_cncpp_point_y`, point)
}

cncpp_point_z <- function(point) {
    .Call(`_cncppr_cncpp_point_z`, point)
}

cncpp_point_set_x <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_x`, point, value))
}

cncpp_point_set_y <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_y`, point, value))
}

cncpp_point_set_z <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_z`, point, value))
}

cncpp_point_vec <- function(point) {
    .Call(`_cncppr_cncpp_point_vec`, point)
}

cncpp_point_length <- function(point) {
    .Call(`_cncppr_cncpp_point_length`, point)
}

cncpp_point_delta <- function(point, other) {
    .Call(`_cncppr_cncpp_point_delta`, point, other)
}

cncpp_point_add <- function(point, other) {
    .Call(`_cncppr_cncpp_point_add`, point, other)
}

cncpp_point_modal <- function(point, other) {
    invisible(.Call(`_cncppr_cncpp_point_modal`, point, other))
}

cncpp_block_create <- function(line, previous) {
    .Call(`_cncppr_cncpp_block_create`, line, previous)
}

cncpp_block_parse <- function(block) {
    .Call(`_cncppr_cncpp_block_parse`, block)
}

cncpp_block_desc <- function(block, colored) {
    .Call(`_cncppr_cncpp_block_desc`, block, colored)
}

cncpp_block_line <- function(block) {
    .Call(`_cncppr_cncpp_block_line`, block)
}

cncpp_block_n <- function(block) {
    .Call(`_cncppr_cncpp_block_n`, block)
}

cncpp_block_dt <- function(block) {
    .Call(`_cncppr_cncpp_block_dt`, block)
}

cncpp_block_type <- function(block) {
    .Call(`_cncppr_cncpp_block_type`, block)
}

cncpp_block_tool <- function(block) {
    .Call(`_cncppr_cncpp_block_tool`, block)
}

cncpp_block_feedrate <- function(block) {
    .Call(`_cncppr_cncpp_block_feedrate`, block)
}

cncpp_block_arc_feedrate <- function(block) {
    .Call(`_cncppr_cncpp_block_arc_feedrate`, block)
}

cncpp_block_spindle <- function(block) {
    .Call(`_cncppr_cncpp_block_spindle`, block)
}

cncpp_block_length <- function(block) {
    .Call(`_cncppr_cncpp_block_length`, block)
}

cncpp_block_target <- function(block) {
    .Call(`_cncppr_cncpp_block_target`, block)
}

cncpp_block_center <- function(block) {
    .Call(`_cncppr_cncpp_block_center`, block)
}

cncpp_block_delta <- function(block) {
    .Call(`_cncppr_cncpp_block_delta`, block)
}

cncpp_block_m <- function(block) {
    .Call(`_cncppr_cncpp_block_m`, block)
}

cncpp_block_profile <- function(block) {
    .Call(`_cncppr_cncpp_block_profile`, block)
}

cncpp_block_parsed <- function(block) {
    .Call(`_cncppr_cncpp_block_parsed`, block)
}

cncpp_block_r <- function(block) {
    .Call(`_cncppr_cncpp_block_r`, block)
}

cncpp_block_lambda <- function(block, time) {
    .Call(`_cncppr_cncpp_block_lambda`, block, time)
}

cncpp_block_interpolate_lambda <- function(block, lambda) {
    .Call(`_cncppr_cncpp_block_interpolate_lambda`, block, lambda)
}

cncpp_block_interpolate_time <- function(block, time) {
    .Call(`_cncppr_cncpp_block_interpolate_time`, block, time)
}

cncpp_block_walk <- function(block) {
    .Call(`_cncppr_cncpp_block_walk`, block)
}

cncpp_block_summary <- function(block) {
    .Call(`_cncppr_cncpp_block_summary`, block)
}

cncpp_program_create <- function(filename, machine) {
    .Call(`_cncppr_cncpp_program_create`, filename, machine)
}

cncpp_program_desc <- function(program, colored) {
    .Call(`_cncppr_cncpp_program_desc`, program, colored)
}

cncpp_program_load <- function(program, filename, append) {
    invisible(.Call(`_cncppr_cncpp_program_load`, program, filename, append))
}

cncpp_program_append <- function(program, lines) {
    invisible(.Call(`_cncppr_cncpp_program_append`, program, lines))
}

cncpp_program_reset <- function(program) {
    invisible(.Call(`_cncppr_cncpp_program_reset`, program))
}

cncpp_program_size <- function(program) {
    .Call(`_cncppr_cncpp_program_size`, program)
}

cncpp_program_done <- function(program) {
    .Call(`_cncppr_cncpp_program_done`, program)
}

cncpp_program_lines <- function(program) {
    .Call(`_cncppr_cncpp_program_lines`, program)
}

cncpp_program_blocks <- function(program) {
    .Call(`_cncppr_cncpp_program_blocks`, program)
}

cncpp_program_summary <- function(program) {
    .Call(`_cncppr_cncpp_program_summary`, program)
}

cncpp_program_current <- function(program) {
    .Call(`_cncppr_cncpp_program_current`, program)
}

cncpp_program_load_next <- function(program) {
    .Call(`_cncppr_cncpp_program_load_next`, program)
}

cncpp_program_rewind <- function(program) {
    invisible(.Call(`_cncppr_cncpp_program_rewind`, program))
}

cncpp_program_walk <- function(program) {
    .Call(`_cncppr_cncpp_program_walk`, program)
}

