# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cncpp_point_create <- function(x, y, z) {
    .Call(`_cncppr_cncpp_point_create`, x, y, z)
}

cncpp_point_desc <- function(point, colored) {
    .Call(`_cncppr_cncpp_point_desc`, point, colored)
}

cncpp_point_is_complete <- function(point) {
    .Call(`_cncppr_cncpp_point_is_complete`, point)
}

cncpp_point_reset <- function(point) {
    invisible(.Call(`_cncppr_cncpp_point_reset`, point))
}

cncpp_point_x <- function(point) {
    .Call(`_cncppr_cncpp_point_x`, point)
}

cncpp_point_y <- function(point) {
    .Call(`_cncppr_cncpp_point_y`, point)
}

cncpp_point_z <- function(point) {
    .Call(`_cncppr_cncpp_point_z`, point)
}

cncpp_point_set_x <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_x`, point, value))
}

cncpp_point_set_y <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_y`, point, value))
}

cncpp_point_set_z <- function(point, value) {
    invisible(.Call(`_cncppr_cncpp_point_set_z`, point, value))
}

cncpp_point_vec <- function(point) {
    .Call(`_cncppr_cncpp_point_vec`, point)
}

cncpp_point_length <- function(point) {
    .Call(`_cncppr_cncpp_point_length`, point)
}

cncpp_point_delta <- function(point, other) {
    .Call(`_cncppr_cncpp_point_delta`, point, other)
}

cncpp_point_add <- function(point, other) {
    .Call(`_cncppr_cncpp_point_add`, point, other)
}

cncpp_point_modal <- function(point, other) {
    invisible(.Call(`_cncppr_cncpp_point_modal`, point, other))
}

cncpp_block_create <- function(line, previous) {
    .Call(`_cncppr_cncpp_block_create`, line, previous)
}

cncpp_block_parse <- function(block) {
    .Call(`_cncppr_cncpp_block_parse`, block)
}

cncpp_block_desc <- function(block, colored) {
    .Call(`_cncppr_cncpp_block_desc`, block, colored)
}

cncpp_block_line <- function(block) {
    .Call(`_cncppr_cncpp_block_line`, block)
}

cncpp_block_n <- function(block) {
    .Call(`_cncppr_cncpp_block_n`, block)
}

cncpp_block_dt <- function(block) {
    .Call(`_cncppr_cncpp_block_dt`, block)
}

cncpp_block_type <- function(block) {
    .Call(`_cncppr_cncpp_block_type`, block)
}

cncpp_block_tool <- function(block) {
    .Call(`_cncppr_cncpp_block_tool`, block)
}

cncpp_block_feedrate <- function(block) {
    .Call(`_cncppr_cncpp_block_feedrate`, block)
}

cncpp_block_arc_feedrate <- function(block) {
    .Call(`_cncppr_cncpp_block_arc_feedrate`, block)
}

cncpp_block_spindle <- function(block) {
    .Call(`_cncppr_cncpp_block_spindle`, block)
}

cncpp_block_length <- function(block) {
    .Call(`_cncppr_cncpp_block_length`, block)
}

cncpp_block_target <- function(block) {
    .Call(`_cncppr_cncpp_block_target`, block)
}

cncpp_block_center <- function(block) {
    .Call(`_cncppr_cncpp_block_center`, block)
}

cncpp_block_delta <- function(block) {
    .Call(`_cncppr_cncpp_block_delta`, block)
}

cncpp_block_m <- function(block) {
    .Call(`_cncppr_cncpp_block_m`, block)
}

cncpp_block_profile <- function(block) {
    .Call(`_cncppr_cncpp_block_profile`, block)
}

cncpp_block_parsed <- function(block) {
    .Call(`_cncppr_cncpp_block_parsed`, block)
}

cncpp_block_r <- function(block) {
    .Call(`_cncppr_cncpp_block_r`, block)
}

cncpp_block_lambda <- function(block, time) {
    .Call(`_cncppr_cncpp_block_lambda`, block, time)
}

cncpp_block_interpolate_lambda <- function(block, lambda) {
    .Call(`_cncppr_cncpp_block_interpolate_lambda`, block, lambda)
}

cncpp_block_interpolate_time <- function(block, time) {
    .Call(`_cncppr_cncpp_block_interpolate_time`, block, time)
}

cncpp_block_walk <- function(block) {
    .Call(`_cncppr_cncpp_block_walk`, block)
}

cncpp_block_summary <- function(block) {
    .Call(`_cncppr_cncpp_block_summary`, block)
}

