#   ____                                      
#  / ___|___  _ __ ___  _ __ ___   ___  _ __  
# | |   / _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \ 
# | |__| (_) | | | | | | | | | | | (_) | | | |
#  \____\___/|_| |_| |_|_| |_| |_|\___/|_| |_|
# 


[agents]
# Settings shared by all agents
frontend_address = "tcp://localhost:9090"
backend_address = "tcp://localhost:9091"
settings_address = "tcp://localhost:9092"
timecode_fps = 25


#  __  __                   _ _ _   _     _      
# |  \/  | ___  _ __   ___ | (_) |_| |__ (_) ___ 
# | |\/| |/ _ \| '_ \ / _ \| | | __| '_ \| |/ __|
# | |  | | (_) | | | | (_) | | | |_| | | | | (__ 
# |_|  |_|\___/|_| |_|\___/|_|_|\__|_| |_|_|\___|
#                                                

[broker]
frontend_address = "tcp://*:9090"
backend_address = "tcp://*:9091"
settings_address = "tcp://*:9092"
prefer_loopback_for_local_services = true
# The followings are only needed if using CURVE encryption
# auth_verbose = false
# ip_whitelist = ["127.0.0.1"] # default is empty (allow all)


[perf_assess]
pub_topic = "perf_assess"

[python]
pub_topic = "machine_tool_control"
sub_topic = ["fmu_machine_tool"]

#  ____  _             _           
# |  _ \| |_   _  __ _(_)_ __  ___ 
# | |_) | | | | |/ _` | | '_ \/ __|
# |  __/| | |_| | (_| | | | | \__ \
# |_|   |_|\__,_|\__, |_|_| |_|___/
#                |___/             
#


[publish]
pub_topic = "publish"

[feedback]
# Subscribes to ALL topics
sub_topic = [""]
print_width = 0
indent_width = 2

# The FMU machine simulator
[fmu_machine_tool]
period = 5
pub_topic = "fmu_machine_tool"
sub_topic = ["machine_tool_control"]
relative_tol = 1e-4
absolute_tol = 1e-5
hmin_tol = 1e-10
[fmu_machine_tool.parameters]
# default values from FMU
# X axis
XP_pos = 4.0
XI_pos = 0
XD_pos = 0
XN_pos = 1
XP_vel = 3500.0
XI_vel = 0.2
XD_vel = 0
XN_vel = 1
X0 = 0
Xm = 300
Xdc = 0.1
Xsat = 2000
# Y axis
YP_pos = 4.0
YI_pos = 0
YD_pos = 0
YN_pos = 1
YP_vel = 3000.0
YI_vel = 0.2
YD_vel = 0
YN_vel = 1
Y0 = 0
Ym = 100
Ydc = 0.1
Ysat = 2000
# Z axis
ZP_pos = 4.0
ZI_pos = 0
ZD_pos = 0
ZN_pos = 1
ZP_vel = 3000.0
ZI_vel = 0.2
ZD_vel = 0
ZN_vel = 1
Z0 = 0
Zm = 200
Zdc = 0.1
Zsat = 2000
# Sensors resolution
res = 1e-06

# This is the Rerun viewer:
[machinetool]
queue_size=1
sub_topic = ["fmu_machine_tool"]
initial_position = [0, 0, 200]
tool = {length = 100, diameter = 20, z_offset = 50}
