// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cncpp_machine_create
SEXP cncpp_machine_create(SEXP filename);
RcppExport SEXP _cncppr_cncpp_machine_create(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_create(filename));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_desc
std::string cncpp_machine_desc(SEXP machine, bool colored);
RcppExport SEXP _cncppr_cncpp_machine_desc(SEXP machineSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_desc(machine, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_load
void cncpp_machine_load(SEXP machine, std::string filename);
RcppExport SEXP _cncppr_cncpp_machine_load(SEXP machineSEXP, SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    cncpp_machine_load(machine, filename);
    return R_NilValue;
END_RCPP
}
// cncpp_machine_quantize
Rcpp::List cncpp_machine_quantize(SEXP machine, double time);
RcppExport SEXP _cncppr_cncpp_machine_quantize(SEXP machineSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_quantize(machine, time));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_A
double cncpp_machine_A(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_A(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_A(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_tq
double cncpp_machine_tq(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_tq(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_tq(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_fmax
double cncpp_machine_fmax(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_fmax(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_fmax(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_error
double cncpp_machine_error(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_error(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_error(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_max_error
double cncpp_machine_max_error(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_max_error(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_max_error(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_zero
SEXP cncpp_machine_zero(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_zero(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_zero(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_offset
SEXP cncpp_machine_offset(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_offset(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_offset(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_setpoint
SEXP cncpp_machine_setpoint(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_setpoint(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_setpoint(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_position
SEXP cncpp_machine_position(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_position(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_position(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_machine_set_setpoint
void cncpp_machine_set_setpoint(SEXP machine, SEXP point);
RcppExport SEXP _cncppr_cncpp_machine_set_setpoint(SEXP machineSEXP, SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    cncpp_machine_set_setpoint(machine, point);
    return R_NilValue;
END_RCPP
}
// cncpp_machine_set_setpoint_xyz
void cncpp_machine_set_setpoint_xyz(SEXP machine, double x, double y, double z);
RcppExport SEXP _cncppr_cncpp_machine_set_setpoint_xyz(SEXP machineSEXP, SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    cncpp_machine_set_setpoint_xyz(machine, x, y, z);
    return R_NilValue;
END_RCPP
}
// cncpp_machine_set_position
void cncpp_machine_set_position(SEXP machine, SEXP point);
RcppExport SEXP _cncppr_cncpp_machine_set_position(SEXP machineSEXP, SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    cncpp_machine_set_position(machine, point);
    return R_NilValue;
END_RCPP
}
// cncpp_machine_summary
Rcpp::List cncpp_machine_summary(SEXP machine);
RcppExport SEXP _cncppr_cncpp_machine_summary(SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_machine_summary(machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_create
SEXP cncpp_point_create(SEXP x, SEXP y, SEXP z);
RcppExport SEXP _cncppr_cncpp_point_create(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_create(x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_desc
std::string cncpp_point_desc(SEXP point, bool colored);
RcppExport SEXP _cncppr_cncpp_point_desc(SEXP pointSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_desc(point, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_is_complete
bool cncpp_point_is_complete(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_is_complete(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_is_complete(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_reset
void cncpp_point_reset(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_reset(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    cncpp_point_reset(point);
    return R_NilValue;
END_RCPP
}
// cncpp_point_x
double cncpp_point_x(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_x(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_x(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_y
double cncpp_point_y(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_y(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_y(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_z
double cncpp_point_z(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_z(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_z(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_set_x
void cncpp_point_set_x(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_x(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_x(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_set_y
void cncpp_point_set_y(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_y(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_y(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_set_z
void cncpp_point_set_z(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_z(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_z(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_vec
Rcpp::NumericVector cncpp_point_vec(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_vec(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_vec(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_length
double cncpp_point_length(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_length(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_length(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_delta
SEXP cncpp_point_delta(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_delta(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_delta(point, other));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_add
SEXP cncpp_point_add(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_add(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_add(point, other));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_modal
void cncpp_point_modal(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_modal(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    cncpp_point_modal(point, other);
    return R_NilValue;
END_RCPP
}
// cncpp_block_create
SEXP cncpp_block_create(std::string line, SEXP previous);
RcppExport SEXP _cncppr_cncpp_block_create(SEXP lineSEXP, SEXP previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type line(lineSEXP);
    Rcpp::traits::input_parameter< SEXP >::type previous(previousSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_create(line, previous));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_parse
SEXP cncpp_block_parse(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_parse(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_parse(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_desc
std::string cncpp_block_desc(SEXP block, bool colored);
RcppExport SEXP _cncppr_cncpp_block_desc(SEXP blockSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_desc(block, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_line
std::string cncpp_block_line(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_line(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_line(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_n
R_xlen_t cncpp_block_n(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_n(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_n(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_dt
double cncpp_block_dt(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_dt(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_dt(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_type
Rcpp::List cncpp_block_type(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_type(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_type(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_tool
R_xlen_t cncpp_block_tool(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_tool(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_tool(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_feedrate
double cncpp_block_feedrate(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_feedrate(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_feedrate(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_arc_feedrate
double cncpp_block_arc_feedrate(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_arc_feedrate(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_arc_feedrate(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_spindle
double cncpp_block_spindle(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_spindle(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_spindle(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_length
double cncpp_block_length(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_length(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_length(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_target
SEXP cncpp_block_target(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_target(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_target(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_center
SEXP cncpp_block_center(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_center(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_center(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_delta
SEXP cncpp_block_delta(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_delta(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_delta(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_m
R_xlen_t cncpp_block_m(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_m(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_m(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_profile
Rcpp::List cncpp_block_profile(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_profile(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_profile(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_parsed
bool cncpp_block_parsed(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_parsed(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_parsed(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_r
double cncpp_block_r(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_r(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_r(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_lambda
Rcpp::List cncpp_block_lambda(SEXP block, double time);
RcppExport SEXP _cncppr_cncpp_block_lambda(SEXP blockSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_lambda(block, time));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_interpolate_lambda
SEXP cncpp_block_interpolate_lambda(SEXP block, double lambda);
RcppExport SEXP _cncppr_cncpp_block_interpolate_lambda(SEXP blockSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_interpolate_lambda(block, lambda));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_interpolate_time
Rcpp::List cncpp_block_interpolate_time(SEXP block, double time);
RcppExport SEXP _cncppr_cncpp_block_interpolate_time(SEXP blockSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_interpolate_time(block, time));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_walk
Rcpp::DataFrame cncpp_block_walk(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_walk(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_walk(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_summary
Rcpp::List cncpp_block_summary(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_summary(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_summary(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_create
SEXP cncpp_program_create(SEXP filename, SEXP machine);
RcppExport SEXP _cncppr_cncpp_program_create(SEXP filenameSEXP, SEXP machineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type machine(machineSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_create(filename, machine));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_desc
std::string cncpp_program_desc(SEXP program, bool colored);
RcppExport SEXP _cncppr_cncpp_program_desc(SEXP programSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_desc(program, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_load
void cncpp_program_load(SEXP program, std::string filename, bool append);
RcppExport SEXP _cncppr_cncpp_program_load(SEXP programSEXP, SEXP filenameSEXP, SEXP appendSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< bool >::type append(appendSEXP);
    cncpp_program_load(program, filename, append);
    return R_NilValue;
END_RCPP
}
// cncpp_program_append
void cncpp_program_append(SEXP program, Rcpp::CharacterVector lines);
RcppExport SEXP _cncppr_cncpp_program_append(SEXP programSEXP, SEXP linesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type lines(linesSEXP);
    cncpp_program_append(program, lines);
    return R_NilValue;
END_RCPP
}
// cncpp_program_reset
void cncpp_program_reset(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_reset(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    cncpp_program_reset(program);
    return R_NilValue;
END_RCPP
}
// cncpp_program_size
R_xlen_t cncpp_program_size(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_size(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_size(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_done
bool cncpp_program_done(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_done(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_done(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_lines
Rcpp::CharacterVector cncpp_program_lines(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_lines(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_lines(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_blocks
Rcpp::List cncpp_program_blocks(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_blocks(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_blocks(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_summary
Rcpp::List cncpp_program_summary(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_summary(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_summary(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_current
SEXP cncpp_program_current(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_current(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_current(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_load_next
SEXP cncpp_program_load_next(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_load_next(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_load_next(program));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_program_rewind
void cncpp_program_rewind(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_rewind(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    cncpp_program_rewind(program);
    return R_NilValue;
END_RCPP
}
// cncpp_program_walk
Rcpp::DataFrame cncpp_program_walk(SEXP program);
RcppExport SEXP _cncppr_cncpp_program_walk(SEXP programSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type program(programSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_program_walk(program));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cncppr_cncpp_machine_create", (DL_FUNC) &_cncppr_cncpp_machine_create, 1},
    {"_cncppr_cncpp_machine_desc", (DL_FUNC) &_cncppr_cncpp_machine_desc, 2},
    {"_cncppr_cncpp_machine_load", (DL_FUNC) &_cncppr_cncpp_machine_load, 2},
    {"_cncppr_cncpp_machine_quantize", (DL_FUNC) &_cncppr_cncpp_machine_quantize, 2},
    {"_cncppr_cncpp_machine_A", (DL_FUNC) &_cncppr_cncpp_machine_A, 1},
    {"_cncppr_cncpp_machine_tq", (DL_FUNC) &_cncppr_cncpp_machine_tq, 1},
    {"_cncppr_cncpp_machine_fmax", (DL_FUNC) &_cncppr_cncpp_machine_fmax, 1},
    {"_cncppr_cncpp_machine_error", (DL_FUNC) &_cncppr_cncpp_machine_error, 1},
    {"_cncppr_cncpp_machine_max_error", (DL_FUNC) &_cncppr_cncpp_machine_max_error, 1},
    {"_cncppr_cncpp_machine_zero", (DL_FUNC) &_cncppr_cncpp_machine_zero, 1},
    {"_cncppr_cncpp_machine_offset", (DL_FUNC) &_cncppr_cncpp_machine_offset, 1},
    {"_cncppr_cncpp_machine_setpoint", (DL_FUNC) &_cncppr_cncpp_machine_setpoint, 1},
    {"_cncppr_cncpp_machine_position", (DL_FUNC) &_cncppr_cncpp_machine_position, 1},
    {"_cncppr_cncpp_machine_set_setpoint", (DL_FUNC) &_cncppr_cncpp_machine_set_setpoint, 2},
    {"_cncppr_cncpp_machine_set_setpoint_xyz", (DL_FUNC) &_cncppr_cncpp_machine_set_setpoint_xyz, 4},
    {"_cncppr_cncpp_machine_set_position", (DL_FUNC) &_cncppr_cncpp_machine_set_position, 2},
    {"_cncppr_cncpp_machine_summary", (DL_FUNC) &_cncppr_cncpp_machine_summary, 1},
    {"_cncppr_cncpp_point_create", (DL_FUNC) &_cncppr_cncpp_point_create, 3},
    {"_cncppr_cncpp_point_desc", (DL_FUNC) &_cncppr_cncpp_point_desc, 2},
    {"_cncppr_cncpp_point_is_complete", (DL_FUNC) &_cncppr_cncpp_point_is_complete, 1},
    {"_cncppr_cncpp_point_reset", (DL_FUNC) &_cncppr_cncpp_point_reset, 1},
    {"_cncppr_cncpp_point_x", (DL_FUNC) &_cncppr_cncpp_point_x, 1},
    {"_cncppr_cncpp_point_y", (DL_FUNC) &_cncppr_cncpp_point_y, 1},
    {"_cncppr_cncpp_point_z", (DL_FUNC) &_cncppr_cncpp_point_z, 1},
    {"_cncppr_cncpp_point_set_x", (DL_FUNC) &_cncppr_cncpp_point_set_x, 2},
    {"_cncppr_cncpp_point_set_y", (DL_FUNC) &_cncppr_cncpp_point_set_y, 2},
    {"_cncppr_cncpp_point_set_z", (DL_FUNC) &_cncppr_cncpp_point_set_z, 2},
    {"_cncppr_cncpp_point_vec", (DL_FUNC) &_cncppr_cncpp_point_vec, 1},
    {"_cncppr_cncpp_point_length", (DL_FUNC) &_cncppr_cncpp_point_length, 1},
    {"_cncppr_cncpp_point_delta", (DL_FUNC) &_cncppr_cncpp_point_delta, 2},
    {"_cncppr_cncpp_point_add", (DL_FUNC) &_cncppr_cncpp_point_add, 2},
    {"_cncppr_cncpp_point_modal", (DL_FUNC) &_cncppr_cncpp_point_modal, 2},
    {"_cncppr_cncpp_block_create", (DL_FUNC) &_cncppr_cncpp_block_create, 2},
    {"_cncppr_cncpp_block_parse", (DL_FUNC) &_cncppr_cncpp_block_parse, 1},
    {"_cncppr_cncpp_block_desc", (DL_FUNC) &_cncppr_cncpp_block_desc, 2},
    {"_cncppr_cncpp_block_line", (DL_FUNC) &_cncppr_cncpp_block_line, 1},
    {"_cncppr_cncpp_block_n", (DL_FUNC) &_cncppr_cncpp_block_n, 1},
    {"_cncppr_cncpp_block_dt", (DL_FUNC) &_cncppr_cncpp_block_dt, 1},
    {"_cncppr_cncpp_block_type", (DL_FUNC) &_cncppr_cncpp_block_type, 1},
    {"_cncppr_cncpp_block_tool", (DL_FUNC) &_cncppr_cncpp_block_tool, 1},
    {"_cncppr_cncpp_block_feedrate", (DL_FUNC) &_cncppr_cncpp_block_feedrate, 1},
    {"_cncppr_cncpp_block_arc_feedrate", (DL_FUNC) &_cncppr_cncpp_block_arc_feedrate, 1},
    {"_cncppr_cncpp_block_spindle", (DL_FUNC) &_cncppr_cncpp_block_spindle, 1},
    {"_cncppr_cncpp_block_length", (DL_FUNC) &_cncppr_cncpp_block_length, 1},
    {"_cncppr_cncpp_block_target", (DL_FUNC) &_cncppr_cncpp_block_target, 1},
    {"_cncppr_cncpp_block_center", (DL_FUNC) &_cncppr_cncpp_block_center, 1},
    {"_cncppr_cncpp_block_delta", (DL_FUNC) &_cncppr_cncpp_block_delta, 1},
    {"_cncppr_cncpp_block_m", (DL_FUNC) &_cncppr_cncpp_block_m, 1},
    {"_cncppr_cncpp_block_profile", (DL_FUNC) &_cncppr_cncpp_block_profile, 1},
    {"_cncppr_cncpp_block_parsed", (DL_FUNC) &_cncppr_cncpp_block_parsed, 1},
    {"_cncppr_cncpp_block_r", (DL_FUNC) &_cncppr_cncpp_block_r, 1},
    {"_cncppr_cncpp_block_lambda", (DL_FUNC) &_cncppr_cncpp_block_lambda, 2},
    {"_cncppr_cncpp_block_interpolate_lambda", (DL_FUNC) &_cncppr_cncpp_block_interpolate_lambda, 2},
    {"_cncppr_cncpp_block_interpolate_time", (DL_FUNC) &_cncppr_cncpp_block_interpolate_time, 2},
    {"_cncppr_cncpp_block_walk", (DL_FUNC) &_cncppr_cncpp_block_walk, 1},
    {"_cncppr_cncpp_block_summary", (DL_FUNC) &_cncppr_cncpp_block_summary, 1},
    {"_cncppr_cncpp_program_create", (DL_FUNC) &_cncppr_cncpp_program_create, 2},
    {"_cncppr_cncpp_program_desc", (DL_FUNC) &_cncppr_cncpp_program_desc, 2},
    {"_cncppr_cncpp_program_load", (DL_FUNC) &_cncppr_cncpp_program_load, 3},
    {"_cncppr_cncpp_program_append", (DL_FUNC) &_cncppr_cncpp_program_append, 2},
    {"_cncppr_cncpp_program_reset", (DL_FUNC) &_cncppr_cncpp_program_reset, 1},
    {"_cncppr_cncpp_program_size", (DL_FUNC) &_cncppr_cncpp_program_size, 1},
    {"_cncppr_cncpp_program_done", (DL_FUNC) &_cncppr_cncpp_program_done, 1},
    {"_cncppr_cncpp_program_lines", (DL_FUNC) &_cncppr_cncpp_program_lines, 1},
    {"_cncppr_cncpp_program_blocks", (DL_FUNC) &_cncppr_cncpp_program_blocks, 1},
    {"_cncppr_cncpp_program_summary", (DL_FUNC) &_cncppr_cncpp_program_summary, 1},
    {"_cncppr_cncpp_program_current", (DL_FUNC) &_cncppr_cncpp_program_current, 1},
    {"_cncppr_cncpp_program_load_next", (DL_FUNC) &_cncppr_cncpp_program_load_next, 1},
    {"_cncppr_cncpp_program_rewind", (DL_FUNC) &_cncppr_cncpp_program_rewind, 1},
    {"_cncppr_cncpp_program_walk", (DL_FUNC) &_cncppr_cncpp_program_walk, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cncppr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
