// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cncpp_point_create
SEXP cncpp_point_create(SEXP x, SEXP y, SEXP z);
RcppExport SEXP _cncppr_cncpp_point_create(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_create(x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_desc
std::string cncpp_point_desc(SEXP point, bool colored);
RcppExport SEXP _cncppr_cncpp_point_desc(SEXP pointSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_desc(point, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_is_complete
bool cncpp_point_is_complete(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_is_complete(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_is_complete(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_reset
void cncpp_point_reset(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_reset(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    cncpp_point_reset(point);
    return R_NilValue;
END_RCPP
}
// cncpp_point_x
double cncpp_point_x(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_x(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_x(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_y
double cncpp_point_y(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_y(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_y(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_z
double cncpp_point_z(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_z(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_z(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_set_x
void cncpp_point_set_x(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_x(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_x(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_set_y
void cncpp_point_set_y(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_y(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_y(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_set_z
void cncpp_point_set_z(SEXP point, double value);
RcppExport SEXP _cncppr_cncpp_point_set_z(SEXP pointSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    cncpp_point_set_z(point, value);
    return R_NilValue;
END_RCPP
}
// cncpp_point_vec
Rcpp::NumericVector cncpp_point_vec(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_vec(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_vec(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_length
double cncpp_point_length(SEXP point);
RcppExport SEXP _cncppr_cncpp_point_length(SEXP pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_length(point));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_delta
SEXP cncpp_point_delta(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_delta(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_delta(point, other));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_add
SEXP cncpp_point_add(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_add(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_point_add(point, other));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_point_modal
void cncpp_point_modal(SEXP point, SEXP other);
RcppExport SEXP _cncppr_cncpp_point_modal(SEXP pointSEXP, SEXP otherSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type point(pointSEXP);
    Rcpp::traits::input_parameter< SEXP >::type other(otherSEXP);
    cncpp_point_modal(point, other);
    return R_NilValue;
END_RCPP
}
// cncpp_block_create
SEXP cncpp_block_create(std::string line, SEXP previous);
RcppExport SEXP _cncppr_cncpp_block_create(SEXP lineSEXP, SEXP previousSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type line(lineSEXP);
    Rcpp::traits::input_parameter< SEXP >::type previous(previousSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_create(line, previous));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_parse
SEXP cncpp_block_parse(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_parse(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_parse(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_desc
std::string cncpp_block_desc(SEXP block, bool colored);
RcppExport SEXP _cncppr_cncpp_block_desc(SEXP blockSEXP, SEXP coloredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< bool >::type colored(coloredSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_desc(block, colored));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_line
std::string cncpp_block_line(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_line(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_line(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_n
R_xlen_t cncpp_block_n(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_n(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_n(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_dt
double cncpp_block_dt(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_dt(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_dt(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_type
Rcpp::List cncpp_block_type(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_type(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_type(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_tool
R_xlen_t cncpp_block_tool(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_tool(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_tool(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_feedrate
double cncpp_block_feedrate(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_feedrate(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_feedrate(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_arc_feedrate
double cncpp_block_arc_feedrate(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_arc_feedrate(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_arc_feedrate(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_spindle
double cncpp_block_spindle(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_spindle(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_spindle(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_length
double cncpp_block_length(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_length(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_length(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_target
SEXP cncpp_block_target(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_target(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_target(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_center
SEXP cncpp_block_center(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_center(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_center(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_delta
SEXP cncpp_block_delta(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_delta(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_delta(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_m
R_xlen_t cncpp_block_m(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_m(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_m(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_profile
Rcpp::List cncpp_block_profile(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_profile(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_profile(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_parsed
bool cncpp_block_parsed(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_parsed(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_parsed(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_r
double cncpp_block_r(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_r(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_r(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_lambda
Rcpp::List cncpp_block_lambda(SEXP block, double time);
RcppExport SEXP _cncppr_cncpp_block_lambda(SEXP blockSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_lambda(block, time));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_interpolate_lambda
SEXP cncpp_block_interpolate_lambda(SEXP block, double lambda);
RcppExport SEXP _cncppr_cncpp_block_interpolate_lambda(SEXP blockSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_interpolate_lambda(block, lambda));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_interpolate_time
Rcpp::List cncpp_block_interpolate_time(SEXP block, double time);
RcppExport SEXP _cncppr_cncpp_block_interpolate_time(SEXP blockSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_interpolate_time(block, time));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_walk
Rcpp::DataFrame cncpp_block_walk(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_walk(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_walk(block));
    return rcpp_result_gen;
END_RCPP
}
// cncpp_block_summary
Rcpp::List cncpp_block_summary(SEXP block);
RcppExport SEXP _cncppr_cncpp_block_summary(SEXP blockSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type block(blockSEXP);
    rcpp_result_gen = Rcpp::wrap(cncpp_block_summary(block));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cncppr_cncpp_point_create", (DL_FUNC) &_cncppr_cncpp_point_create, 3},
    {"_cncppr_cncpp_point_desc", (DL_FUNC) &_cncppr_cncpp_point_desc, 2},
    {"_cncppr_cncpp_point_is_complete", (DL_FUNC) &_cncppr_cncpp_point_is_complete, 1},
    {"_cncppr_cncpp_point_reset", (DL_FUNC) &_cncppr_cncpp_point_reset, 1},
    {"_cncppr_cncpp_point_x", (DL_FUNC) &_cncppr_cncpp_point_x, 1},
    {"_cncppr_cncpp_point_y", (DL_FUNC) &_cncppr_cncpp_point_y, 1},
    {"_cncppr_cncpp_point_z", (DL_FUNC) &_cncppr_cncpp_point_z, 1},
    {"_cncppr_cncpp_point_set_x", (DL_FUNC) &_cncppr_cncpp_point_set_x, 2},
    {"_cncppr_cncpp_point_set_y", (DL_FUNC) &_cncppr_cncpp_point_set_y, 2},
    {"_cncppr_cncpp_point_set_z", (DL_FUNC) &_cncppr_cncpp_point_set_z, 2},
    {"_cncppr_cncpp_point_vec", (DL_FUNC) &_cncppr_cncpp_point_vec, 1},
    {"_cncppr_cncpp_point_length", (DL_FUNC) &_cncppr_cncpp_point_length, 1},
    {"_cncppr_cncpp_point_delta", (DL_FUNC) &_cncppr_cncpp_point_delta, 2},
    {"_cncppr_cncpp_point_add", (DL_FUNC) &_cncppr_cncpp_point_add, 2},
    {"_cncppr_cncpp_point_modal", (DL_FUNC) &_cncppr_cncpp_point_modal, 2},
    {"_cncppr_cncpp_block_create", (DL_FUNC) &_cncppr_cncpp_block_create, 2},
    {"_cncppr_cncpp_block_parse", (DL_FUNC) &_cncppr_cncpp_block_parse, 1},
    {"_cncppr_cncpp_block_desc", (DL_FUNC) &_cncppr_cncpp_block_desc, 2},
    {"_cncppr_cncpp_block_line", (DL_FUNC) &_cncppr_cncpp_block_line, 1},
    {"_cncppr_cncpp_block_n", (DL_FUNC) &_cncppr_cncpp_block_n, 1},
    {"_cncppr_cncpp_block_dt", (DL_FUNC) &_cncppr_cncpp_block_dt, 1},
    {"_cncppr_cncpp_block_type", (DL_FUNC) &_cncppr_cncpp_block_type, 1},
    {"_cncppr_cncpp_block_tool", (DL_FUNC) &_cncppr_cncpp_block_tool, 1},
    {"_cncppr_cncpp_block_feedrate", (DL_FUNC) &_cncppr_cncpp_block_feedrate, 1},
    {"_cncppr_cncpp_block_arc_feedrate", (DL_FUNC) &_cncppr_cncpp_block_arc_feedrate, 1},
    {"_cncppr_cncpp_block_spindle", (DL_FUNC) &_cncppr_cncpp_block_spindle, 1},
    {"_cncppr_cncpp_block_length", (DL_FUNC) &_cncppr_cncpp_block_length, 1},
    {"_cncppr_cncpp_block_target", (DL_FUNC) &_cncppr_cncpp_block_target, 1},
    {"_cncppr_cncpp_block_center", (DL_FUNC) &_cncppr_cncpp_block_center, 1},
    {"_cncppr_cncpp_block_delta", (DL_FUNC) &_cncppr_cncpp_block_delta, 1},
    {"_cncppr_cncpp_block_m", (DL_FUNC) &_cncppr_cncpp_block_m, 1},
    {"_cncppr_cncpp_block_profile", (DL_FUNC) &_cncppr_cncpp_block_profile, 1},
    {"_cncppr_cncpp_block_parsed", (DL_FUNC) &_cncppr_cncpp_block_parsed, 1},
    {"_cncppr_cncpp_block_r", (DL_FUNC) &_cncppr_cncpp_block_r, 1},
    {"_cncppr_cncpp_block_lambda", (DL_FUNC) &_cncppr_cncpp_block_lambda, 2},
    {"_cncppr_cncpp_block_interpolate_lambda", (DL_FUNC) &_cncppr_cncpp_block_interpolate_lambda, 2},
    {"_cncppr_cncpp_block_interpolate_time", (DL_FUNC) &_cncppr_cncpp_block_interpolate_time, 2},
    {"_cncppr_cncpp_block_walk", (DL_FUNC) &_cncppr_cncpp_block_walk, 1},
    {"_cncppr_cncpp_block_summary", (DL_FUNC) &_cncppr_cncpp_block_summary, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cncppr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
