/******************************************************************************
Finite State Machine
Project: cncpp
Description: CNC

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 0.0.0
Generation date: 2026-05-06 13:05:07
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  5 transition functions
Generated with command:mads fsm -p cncpp --cpp -o src/fsm -k stop src/fsm.dot
******************************************************************************/
    
using namespace std;
    
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace cncpp {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE, STATE_STOP
template<class T> 
state_t do_init(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_LOAD_BLOCK, STATE_STOP, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_LOAD_BLOCK
// valid return states: STATE_NO_MOTION, STATE_RAPID_MOTION, STATE_INTERP_MOTION, STATE_IDLE
template<class T> 
state_t do_load_block(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_RAPID_MOTION
// valid return states: NO_CHANGE, STATE_RAPID_MOTION, STATE_LOAD_BLOCK
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_rapid_motion(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_INTERP_MOTION
// valid return states: NO_CHANGE, STATE_INTERP_MOTION, STATE_LOAD_BLOCK
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_interp_motion(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_NO_MOTION
// valid return states: STATE_LOAD_BLOCK
template<class T> 
state_t do_no_motion(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}

// Function to be executed in state STATE_GO_TO_ZERO
// valid return states: NO_CHANGE, STATE_GO_TO_ZERO, STATE_IDLE
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_go_to_zero(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from idle to load_block
template<class T>
void reset(T &data) {
  /* Your Code Here */
}

// This function is called in 2 transitions:
// 1. from load_block to rapid_motion
// 2. from go_to_zero to go_to_zero
template<class T>
void begin_rapid(T &data) {
  /* Your Code Here */
}

// This function is called in 2 transitions:
// 1. from rapid_motion to load_block
// 2. from go_to_zero to idle
template<class T>
void end_rapid(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
template<class T>
void begin_interp(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
template<class T>
void end_interp(T &data) {
  /* Your Code Here */
}


}; // namespace cncpp


// Example usage:
#ifdef TEST_MAIN
/*
  _____ ____  __  __   __  __       _       
 |  ___/ ___||  \/  | |  \/  | __ _(_)_ __  
 | |_  \___ \| |\/| | | |\/| |/ _` | | '_ \ 
 |  _|  ___) | |  | | | |  | | (_| | | | | |
 |_|   |____/|_|  |_| |_|  |_|\__,_|_|_| |_|
                                            
Warning: this is a bare-bones template for a FSM-based agent. It is not meant to be used as-is, but rather to be adapted to the specific needs of the user. 

To compile it with CMake, use the following CMakeLists.txt:
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Find the installed MADS package
find_package(Mads REQUIRED)
message(STATUS "Found Mads: ${Mads_DIR}")

add_executable(fsm path/to/main.cpp)
target_link_libraries(fsm PRIVATE Mads::Mads)
*/
#include <mads.hpp>
#include <agent.hpp>
#include <agent_app.hpp>
#include <thread>
#include <chrono>
#include <filesystem>
#include <nlohmann/json.hpp>
#include "fsm.hpp"

using namespace chrono_literals;
using json = nlohmann::json;

struct FsmData {
  std::unique_ptr<Mads::AgentApp> agent;
};

int main(int argc, char *argv[]) {
  std::filesystem::path exec = argv[0];
  std::string agent_name = exec.stem().string();
  std::string settings_path = "tcp://localhost:9092";
  std::chrono::duration loop_period = 100ms;
  std::chrono::duration receive_timeout = 50ms;
  bool non_blocking = false;

  if (argc > 1) {
    settings_path = argv[1];
  }
  FsmData data = {std::make_unique<Mads::AgentApp>(agent_name, settings_path)};
  // If crypto is needed, properly load keys and enable it
  data.agent->add_common_options();
  data.agent->options()
    ("my-option", "An additional option flag");
 
  auto parsed = data.agent->parse_options(argc, argv);
  if (int rc = Mads::AgentApp::handle_standard_exit_options<Mads::AgentApp>(
          parsed, data.agent->raw_options(), argv);
      rc >= 0) {
    return rc;
  }
 
  data.agent->init(parsed);
  data.agent->enable_events();
  data.agent->connect();
  data.agent->enable_remote_control();
  data.agent->info();

  auto settings = data.agent->get_settings();
  if (settings.contains("period")) {
    loop_period = std::chrono::milliseconds(settings["period"].get<int>());
  }
  if (settings.contains("receive_timeout")) {
    receive_timeout = std::chrono::milliseconds(settings["receive_timeout"].get<int>());
  }
  if (settings.contains("non_blocking")) {
    non_blocking = settings["non_blocking"].get<bool>();
  }
  data.agent->set_receive_timeout(receive_timeout);
  // Deal with further settings as needed

  // Initialize FSM
  auto fsm = cncpp::FiniteStateMachine(&data);
  fsm.set_timing_function([&]() {
    std::this_thread::sleep_for(loop_period);
  });
  fsm.run([&](FsmData &s) {
    // here put everything that shall run at each loop iteration
    data.agent->receive(non_blocking);
    data.agent->remote_control(get<1>(data.agent->last_message()));
  });

  // Shutdown procedure
  data.agent->disconnect();
  data.agent->restart_if_requested(argv);
}
#endif // TEST_MAIN
