/******************************************************************************
Finite State Machine
Project: cncpp
Description: CNC

Generated by gv2fsm, see https://github.com/pbosetti/gv2fsm
gv2fsm version 0.0.0
Generation date: 2026-05-06 13:05:07
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  5 transition functions
Generated with command:mads fsm -p cncpp --cpp -o src/fsm -k stop src/fsm.dot
******************************************************************************/

#include "cncpp.hpp"
#include <rang.hpp>
#include <fmt/format.h>
#include <keystroker.h>

using namespace std;
using namespace fmt;
using namespace rang;
    
// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!


namespace cncpp {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE, STATE_STOP
template<class T> 
state_t do_init(T &data) {
  state_t next_state = cncpp::STATE_IDLE;
  try {
    data.program = make_unique<cncpp::Program>(data.program_file, data.machine.get());
    cerr << "Program loaded: " << endl
         << *data.program << endl;
  } catch (const exception &e) {
    cerr << "Error loading program: " << e.what() << endl;
    next_state = cncpp::STATE_STOP;
  }
  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_LOAD_BLOCK, STATE_STOP, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  
  // 1. wait for user's input
  cerr << "Press <SPACE> to run, Z to go to zero, R to reload program, Q to quit" << endl;

  data.timer->stop();
  char key = keystroker::read_key();
  switch(key) {
    case ' ':
      next_state = cncpp::STATE_LOAD_BLOCK;
      data.program->rewind();
      break;
    case 'r':
    case 'R':
      try {
        data.program->load(data.program_file, false);
        cerr << "Program reloaded:" << endl
             << *data.program << endl;
      } catch (const exception &e) {
        cerr << "Error reloading program: " << e.what() << endl;
      }
      break;
    case 'z':
    case 'Z':
      next_state = cncpp::STATE_GO_TO_ZERO;
      break;
    case 'q':
    case 'Q':
      next_state = cncpp::STATE_STOP;
      break;
    default:
      cerr << "Wrong selection, pick another command" << endl;
  }

  data.timer->start();
  return next_state;
}

// Function to be executed in state STATE_LOAD_BLOCK
// valid return states: STATE_NO_MOTION, STATE_RAPID_MOTION, STATE_INTERP_MOTION, STATE_IDLE
template<class T> 
state_t do_load_block(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  data.program->load_next();
  if (data.program->done()) {
    return cncpp::STATE_IDLE;
  }

  auto &b = *data.program->current();
  cerr << "Loading " << b << endl;
  switch (b.type()) {
    case Block::BlockType::NO_MOTION:
      next_state = cncpp::STATE_NO_MOTION;
      break;
    case Block::BlockType::RAPID:
      next_state = cncpp::STATE_RAPID_MOTION;
      break;
    case Block::BlockType::LINE:
    case Block::BlockType::CWA:
    case Block::BlockType::CCWA:
      next_state = cncpp::STATE_INTERP_MOTION;
      break;
    default:
      next_state = cncpp::STATE_IDLE;
  }

  data.t_tot += data.machine->tq();
  
  return next_state;
}

// Function to be executed in state STATE_RAPID_MOTION
// valid return states: NO_CHANGE, STATE_RAPID_MOTION, STATE_LOAD_BLOCK
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_rapid_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  auto &b = *data.program->current();
  
  cerr << fg::cyan << "Rapid motion block: " << fg::reset
       << b << endl;
  next_state = cncpp::STATE_LOAD_BLOCK;
  
  data.t_tot += data.machine->tq();

  return next_state;
}

// Function to be executed in state STATE_INTERP_MOTION
// valid return states: NO_CHANGE, STATE_INTERP_MOTION, STATE_LOAD_BLOCK
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_interp_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  
  auto &b = *data.program->current();
  data_t lambda, speed;
  data_t tq = data.machine->tq();

  Point tgt = b.interpolate(data.t_blk, lambda, speed);
  Point p = data.machine->position();

  try {
    cout << fmt::format("{:0>3d},{:0>2d},{:.3f},{:.3f},{:.3f},{:.3f},,{:.1f},{:.3f},{:.3f},{:.3f},{:.3f},{:.3f},{:.3f},{:.3f}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), speed, b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), p.x(), p.y(), p.z()) << endl;
  } catch (const bad_optional_access &e) {
    cout << fmt::format("{:0>3d},{:0>2d},{:.3f},{:.3f},{:.3f},{:.3f},,{:.1f},{:.3f},{:.3f},{:.3f},{:.3f},{:>3},{:>3},{:>3}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), speed, b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), "-", "-", "-") << endl;
  }

  if (data.t_blk > b.dt() + tq / 10.0) {
    next_state = cncpp::STATE_LOAD_BLOCK;
  }

  data.t_tot += tq;
  data.t_blk += tq;

  return next_state;
}

// Function to be executed in state STATE_NO_MOTION
// valid return states: STATE_LOAD_BLOCK
template<class T> 
state_t do_no_motion(T &data) {
  state_t next_state = cncpp::STATE_LOAD_BLOCK;
  auto &b = *data.program->current();
  cerr << fg::yellow << "No motion block: " << b << fg::reset << endl;
  
  data.t_tot += data.machine->tq();

  return next_state;
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // reset SIGINT signal handler
  signal(SIGINT, SIG_DFL);

  cerr << fg::red << style::bold << "STOP!" << style::reset << fg::reset << endl;
  
  return next_state;
}

// Function to be executed in state STATE_GO_TO_ZERO
// valid return states: NO_CHANGE, STATE_GO_TO_ZERO, STATE_IDLE
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_go_to_zero(T &data) {
  state_t next_state = cncpp::UNIMPLEMENTED;
  /* Your Code Here */
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from idle to load_block
template<class T>
void reset(T &data) {
  auto &p = data.program;
  p->rewind();
  data.t_tot = 0;
  data.t_blk = 0;
  cout << "n,type,t_to,t_blk,lambda,s,feedrate,acc,xn,yn,zn,x,y,z" << endl;
}

// This function is called in 2 transitions:
// 1. from load_block to rapid_motion
// 2. from go_to_zero to go_to_zero
template<class T>
void begin_rapid(T &data) {
  data.t_blk = 0;
}

// This function is called in 2 transitions:
// 1. from rapid_motion to load_block
// 2. from go_to_zero to idle
template<class T>
void end_rapid(T &data) {
  /* Your Code Here */
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
template<class T>
void begin_interp(T &data) {
  data.t_blk = 0;
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
template<class T>
void end_interp(T &data) {
  /* Your Code Here */
}


}; // namespace cncpp


// Example usage:
#ifdef TEST_MAIN
/*
  _____ ____  __  __   __  __       _       
 |  ___/ ___||  \/  | |  \/  | __ _(_)_ __  
 | |_  \___ \| |\/| | | |\/| |/ _` | | '_ \ 
 |  _|  ___) | |  | | | |  | | (_| | | | | |
 |_|   |____/|_|  |_| |_|  |_|\__,_|_|_| |_|
                                            
Warning: this is a bare-bones template for a FSM-based agent. It is not meant to be used as-is, but rather to be adapted to the specific needs of the user. 

To compile it with CMake, use the following CMakeLists.txt:
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Find the installed MADS package
find_package(Mads REQUIRED)
message(STATUS "Found Mads: ${Mads_DIR}")

add_executable(fsm path/to/main.cpp)
target_link_libraries(fsm PRIVATE Mads::Mads)
*/
#include <mads.hpp>
#include <agent.hpp>
#include <agent_app.hpp>
#include <thread>
#include <chrono>
#include <filesystem>
#include <nlohmann/json.hpp>
#include "fsm.hpp"

using namespace chrono_literals;
using json = nlohmann::json;

struct FsmData {
  std::unique_ptr<Mads::AgentApp> agent;
};

int main(int argc, char *argv[]) {
  std::filesystem::path exec = argv[0];
  std::string agent_name = exec.stem().string();
  std::string settings_path = "tcp://localhost:9092";
  std::chrono::duration loop_period = 100ms;
  std::chrono::duration receive_timeout = 50ms;
  bool non_blocking = false;

  if (argc > 1) {
    settings_path = argv[1];
  }
  FsmData data = {std::make_unique<Mads::AgentApp>(agent_name, settings_path)};
  // If crypto is needed, properly load keys and enable it
  data.agent->add_common_options();
  data.agent->options()
    ("my-option", "An additional option flag");
 
  auto parsed = data.agent->parse_options(argc, argv);
  if (int rc = Mads::AgentApp::handle_standard_exit_options<Mads::AgentApp>(
          parsed, data.agent->raw_options(), argv);
      rc >= 0) {
    return rc;
  }
 
  data.agent->init(parsed);
  data.agent->enable_events();
  data.agent->connect();
  data.agent->enable_remote_control();
  data.agent->info();

  auto settings = data.agent->get_settings();
  if (settings.contains("period")) {
    loop_period = std::chrono::milliseconds(settings["period"].get<int>());
  }
  if (settings.contains("receive_timeout")) {
    receive_timeout = std::chrono::milliseconds(settings["receive_timeout"].get<int>());
  }
  if (settings.contains("non_blocking")) {
    non_blocking = settings["non_blocking"].get<bool>();
  }
  data.agent->set_receive_timeout(receive_timeout);
  // Deal with further settings as needed

  // Initialize FSM
  auto fsm = cncpp::FiniteStateMachine(&data);
  fsm.set_timing_function([&]() {
    std::this_thread::sleep_for(loop_period);
  });
  fsm.run([&](FsmData &s) {
    // here put everything that shall run at each loop iteration
    data.agent->receive(non_blocking);
    data.agent->remote_control(get<1>(data.agent->last_message()));
  });

  // Shutdown procedure
  data.agent->disconnect();
  data.agent->restart_if_requested(argv);
}
#endif // TEST_MAIN
