/******************************************************************************
Finite State Machine
Project: cncpp
Description: CNC

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.5.1
Generation date: 2025-05-15 12:18:46 +0200
Generated from: src/fsm.dot
The finite state machine has:
  8 states
  7 transition functions

******************************************************************************/

#include "cncpp.hpp"
#include <keystroker.h>
#include <rang.hpp>
#include <fmt/core.h>
    
using namespace std;
using namespace rang;
using namespace fmt;

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// struct FSMData {
//   cncpp::machine machine;
//   cncpp::program program;
//   data_t t_tot = 0, t_blk = 0;
//   FSMData(string machine_file) : machine(machine_file), program(&machine);
// }


namespace cncpp {

/*  ____  _        _       
 * / ___|| |_ __ _| |_ ___ 
 * \___ \| __/ _` | __/ _ \
 *  ___) | || (_| | ||  __/
 * |____/ \__\__,_|\__\___|
 *                         
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                             

// Function to be executed in state STATE_INIT
// valid return states: STATE_IDLE, STATE_STOP
template<class T> 
state_t do_init(T &data) {
  state_t next_state = cncpp::STATE_IDLE;
  // STEPS:
  // 1. Connect to the machine via MQTT
  data.machine.connect();

  // 2. Set machine to zero
  data.machine.position(data.machine.zero());
  data.machine.setpoint(data.machine.zero());

  // 3. Message the user
  cerr << fg::green << "Connected to machine "
       << style::bold << data.machine.mqtt_host()
       << style::reset << fg::reset << endl;

  return next_state;
}

// Function to be executed in state STATE_IDLE
// valid return states: NO_CHANGE, STATE_IDLE, STATE_LOAD_BLOCK, STATE_STOP, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_idle(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS:
  // 1. Wait for user input
  cerr << "Press " << fg::green << "<space>" << fg::reset
       << " to run, " << fg::blue << "z" << fg::reset
       << " to go to zero, " << fg::red << "q" << fg::reset
       << " to quit" << endl;

  // 2. select next state according to keypress
  char key = keystroker::read_key();
  switch(key) {
  case ' ':
    next_state = STATE_LOAD_BLOCK;
    data.program.rewind();
    break;
  case 'q':
  case 'Q':
    next_state = STATE_STOP;
    break;
  case 'z':
  case 'Z':
    next_state = STATE_GO_TO_ZERO;
    break;
  default:
    break;
  }

  // 3. reset timings
  data.t_tot = data.t_blk = 0.0;

  // 4. synchronize
  data.machine.sync(false);
  
  return next_state;
}

// Function to be executed in state STATE_STOP
// valid return states: NO_CHANGE
template<class T> 
state_t do_stop(T &data) {
  state_t next_state = cncpp::NO_CHANGE;

  // STEPS:
  // 1. reset signal handler
  signal(SIGINT, SIG_DFL);

  // 2. Disconnect
  data.machine.sync(false);
  data.machine.listen_stop();

  // 3. Message the user
  cerr << fg::red << style::bold << "STOP!" << fg::reset 
       << style::reset << endl;

  return next_state;
}

// Function to be executed in state STATE_LOAD_BLOCK
// valid return states: STATE_IDLE, STATE_NO_MOTION, STATE_RAPID_MOTION, STATE_INTERP_MOTION
template<class T> 
state_t do_load_block(T &data) {
  state_t next_state = cncpp::STATE_RAPID_MOTION;
  
  // STEPS:
  // 1. load the nex block, go back to IDLE if it is the last
  data.program.load_next();
  if (data.program.done()) {
    return STATE_IDLE;
  }

  // 2. check block type
  auto &b = *data.program.current();
  cerr << "Loading " << b.desc() << endl;
  switch (b.type()) {
  case Block::BlockType::NO_MOTION:
    next_state = STATE_NO_MOTION;
    break;
  case Block::BlockType::RAPID:
    next_state = STATE_RAPID_MOTION;
    break;
  case Block::BlockType::LINE:
  case Block::BlockType::CWA:
  case Block::BlockType::CCWA:
    next_state = STATE_INTERP_MOTION;
    break;
  default:
    next_state = STATE_IDLE;
    break;
  }
  
  // 3. Increment total time
  data.t_tot += data.machine.tq();

  return next_state;
}

// Function to be executed in state STATE_GO_TO_ZERO
// valid return states: NO_CHANGE, STATE_IDLE, STATE_GO_TO_ZERO
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_go_to_zero(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  
  // STEPS:
  // 1. synch machine setpoint
  data.machine.sync(true);

  // 2. check if zero has been reached
  if (data.machine.error() < data.machine.max_error()) {
    next_state = STATE_IDLE;
  }

  // 3. Check for CRTL-C
  if (stop_requested) {
    stop_requested = false;
    next_state = STATE_IDLE;
  }

  
  return next_state;
}

// Function to be executed in state STATE_NO_MOTION
// valid return states: STATE_LOAD_BLOCK
template<class T> 
state_t do_no_motion(T &data) {
  state_t next_state = cncpp::STATE_LOAD_BLOCK;
  
  // STEPS:
  // 1. print message
  cerr << fg::yellow << "No motion block: " << fg::reset
       << (*data.program.current()).desc() << endl;
  
  // 2. increment timings
  data.t_tot += data.machine.tq();
  
  return next_state;
}

// Function to be executed in state STATE_RAPID_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_RAPID_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_rapid_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  data_t duration;
  Block &b = *data.program.current();

  // STEPS:
  // 1. Sync the machine
  data.machine.sync(true);

  // 2. Exit if error is small or max time has elapsed
  duration = b.length() / data.machine.fmax() * 60.0 * 2;
  if (data.machine.error() < data.machine.max_error() || data.t_blk > duration) {
    cerr << "Rapid block " << b.desc() << " completed." << endl;
    cerr << "Duration: " << duration << " s" << endl;
    cerr << "Elapsed time: " << data.t_blk << " s" << endl;
    cerr << "Error: " << data.machine.error() << " mm" << endl;
    next_state = cncpp::STATE_LOAD_BLOCK;
  }

  // 3. Exit for CTRL-C
  if (stop_requested) {
    cerr << "Rapid block " << b.desc() << " skipped." << endl;
    stop_requested = false;
    next_state = cncpp::STATE_LOAD_BLOCK;
  }

  // 4. Get current position and print values table
  Point p = data.machine.position();
  Point tgt = b.target();
  data_t lambda = min(data.machine.error() / b.length(), 1.0);
  cout << fmt::format("{:0>3d} {:0>2d} {:.3f} {:.3f} {:.3f} {:.3f} {:.1f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), data.machine.fmax(), b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), p.x(), p.y(), p.z()) << endl;

  // 5. Increment timings
  data.t_tot += data.machine.tq();
  data.t_blk += data.machine.tq();
  
  return next_state;
}

// Function to be executed in state STATE_INTERP_MOTION
// valid return states: NO_CHANGE, STATE_LOAD_BLOCK, STATE_INTERP_MOTION
// SIGINT triggers an emergency transition to STATE_STOP
template<class T> 
state_t do_interp_motion(T &data) {
  state_t next_state = cncpp::NO_CHANGE;
  Block &b = *data.program.current();
  data_t lambda, speed;
  data_t tq = data.machine.tq();

  // STEPS:
  // 1. Interpolate motion
  Point p = data.machine.position();
  Point tgt = b.interpolate(data.t_blk, lambda, speed);

  // 2. Print values table
  cout << fmt::format("{:0>3d} {:0>2d} {:.3f} {:.3f} {:.3f} {:.3f} {:.1f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f} {:.3f}", b.n(), static_cast<int>(b.type()), data.t_tot, data.t_blk, lambda, lambda * b.length(), speed, b.profile().current_acc, tgt.x(), tgt.y(), tgt.z(), p.x(), p.y(), p.z()) << endl;

  // 3. Sync the machine
  data.machine.setpoint(tgt);
  data.machine.sync(false);

  // 4. Check if we are done
  if (data.t_blk > b.dt() + tq / 10) {
    next_state = cncpp::STATE_LOAD_BLOCK;
  }


  // 5. Increment times
  data.t_tot += tq;
  data.t_blk += tq;
  
  return next_state;
}


/*  _____                    _ _   _              
 * |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
 *   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
 *   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
 *   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
 *                                                
 *   __                  _   _                 
 *  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
 * | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
 * |  _| |_| | | | | (__| |_| | (_) | | | \__ \
 * |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
 */                                              

// This function is called in 1 transition:
// 1. from idle to load_block
template<class T>
void reset(T &data) {
  data.t_tot = data.t_blk = 0.0;
  cout << "n type, t_tot t_blk lambda s feedrate acc xr yr zr x y z" << endl;
}

// This function is called in 1 transition:
// 1. from idle to go_to_zero
template<class T>
void begin_zero(T &data) {
  data.machine.listen_start();
  data.machine.setpoint(data.machine.zero());
  data.machine.sync(true);
  cerr << "Going to zero at " << data.machine.zero().desc() << endl;
}

// This function is called in 1 transition:
// 1. from load_block to rapid_motion
template<class T>
void begin_rapid(T &data) {
  Block &b = *data.program.current();
  data.t_blk = 0.0;
  data.machine.listen_start();
  data.machine.setpoint(b.target());
  data.machine.sync(true);
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
template<class T>
void begin_interp(T &data) {
  data.machine.sync(false);
  data.t_blk = 0.0;
}

// This function is called in 1 transition:
// 1. from rapid_motion to load_block
template<class T>
void end_rapid(T &data) {
  data.machine.listen_stop();
  data.machine.sync(false);
}

// This function is called in 1 transition:
// 1. from interp_motion to load_block
template<class T>
void end_interp(T &data) {
  data.machine.sync(false);
}

// This function is called in 1 transition:
// 1. from go_to_zero to idle
template<class T>
void end_zero(T &data) {
  data.machine.listen_stop();
  data.machine.sync(false);
}


}; // namespace cncpp


// Example usage:
#ifdef TEST_MAIN
#include <unistd.h>
#include <thread>

struct Data {
  int count;
};

int main() {
  Data data = {1};
  auto fsm = cncpp::FiniteStateMachine(&data);
  fsm.set_timing_function([]() {
    std::this_thread::sleep_for(std::chrono::seconds(1));
  });
  fsm.run([&](Data &s) {
    std::cout << "State: " << fsm.state() << " data: " << s.count << std::endl;
  });
  return 0;
}
#endif // TEST_MAIN
